version: '3.8'

services:
  # SQL Server (Write DB)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: movie-catalog-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - movie-catalog-network

  # PostgreSQL (Read DB)
  postgres:
    image: postgres:15
    container_name: movie-catalog-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=movie_catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - movie-catalog-network

  # RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: movie-catalog-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - movie-catalog-network

  # PgAdmin (Optional - for PostgreSQL management)
  pgadmin:
    image: dpage/pgadmin4
    container_name: movie-catalog-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@moviedb.com
      - PGADMIN_DEFAULT_PASSWORD=Password123!
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - movie-catalog-network

volumes:
  sqlserver-data:
  postgres-data:
  rabbitmq-data:

networks:
  movie-catalog-network:
    driver: bridge